linters:
  disable-all: true  # 关闭其他linter
  enable:            # 下面是开启的linter列表，之后的英文注释介绍了相应linter的功能
    - errcheck      # Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases
    - gosimple      # Linter for Go source code that specializes in simplifying a code
    - govet         # Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - ineffassign   # Detects when assignments to existing variables are not used
    - staticcheck   # It's a set of rules from staticcheck. It's not the same thing as the staticcheck binary.
    - unused        # Checks Go code for unused constants, variables, functions and types.
    - copyloopvar   # Detects places where loop variables are copied.

linters-settings:
  govet:            # 对于linter govet，我们手动开启了它的某些扫描规则
    enable-all: true
    disable:
      - fieldalignment
issues:
  exclude-dirs:
    - scripts
    - test
    - example
