linters:
  disable-all: true  # Turn off other linters
  enable:
    - errcheck      # Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases
    - gosimple      # Linter for Go source code that specializes in simplifying a code
    - govet         # Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - ineffassign   # Detects when assignments to existing variables are not used
    - staticcheck   # It's a set of rules from staticcheck. It's not the same thing as the staticcheck binary.
    - unused        # Checks Go code for unused constants, variables, functions and types.
    - copyloopvar   # Detects places where loop variables are copied.

linters-settings:
  govet:            # For linter govet, we manually enabled some of its scanning rules
    enable-all: true
    disable:
      - fieldalignment
issues:
  exclude-dirs:
    - scripts
    - test
    - example
